repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      types: [file, python]
    - id: check-added-large-files
-   repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff check --config pyproject.toml --fix --force-exclude
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
      - id: sphinx-lint
        name: sphinx-lint
        entry: poetry run sphinx-lint --enable all --disable leaked-markup --jobs 1 --max-line-length 120 -i docs/_implementations docs
        types: [rst]
        language: system
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format --config pyproject.toml --force-exclude
        require_serial: true
        language: system
        types_or: [python, pyi, jupyter]
      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file pyproject.toml
        types: [file, python]
        language: system
      - id: pyright
        name: pyright
        require_serial: true
        language: system
        entry: poetry run pyright
        types: [file, python]
